faction:
  x: 75
  y: 75
  width: 75
  height: 75

Foundation:
  extends: faction
  file: foundation.svg
The Gilded:
  extends: faction
  file: gilded.svg
Veil Walkers:
  extends: faction
  file: veil_walkers.svg
Fey:
  extends: faction
  file: fey.svg
Abyssal:
  extends: faction
  file: abyssal.svg
Clockwork:
  extends: faction
  file: clockwork.svg

card:
  width: 825
  height: 1125

header:
  width: 795
  height: 70

title:
  x: 17.5
  y: 15
  valign: middle
  extends: header

title_right:
  x: 12.5
  align: right
  extends: title

art:
  x: 12.5
  y: 100
  width: 800
  height: 500

type:
  x: 17.5
  y: 615
  valign: middle
  extends: header

type_right:
  x: 12.5
  align: right
  extends: type
tr: #alias
  extends: type_right

description:
  x: 12.5
  y: 700
  width: 800
  height: 300
  align: center
  valign: middle
  font_size: 12
desc: # alias
  extends: description

attack:
  x: 33
  y: 1021
  width: 87
  height: 87
  font_size: 16
  valign: middle
  align: center
lr: #alias
  extends: attack

influence:
  x: 362.5
  y: 1015
  width: 100
  height: 100
  font_size: 16
  valign: middle
  align: center
lr: #alias
  extends: influence

health:
  x: 683
  y: 1005
  width: 118
  height: 108
  font_size: 16
  valign: middle
  align: center
ll: # alias
  extends: health