[package]
name = "anomaly-cascade"
version = "0.0.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
slotmap = { version = "1.0", features = ["serde"] }
itertools = "0.13"
thiserror = "2"
rand = { version = "0.8.4", features = ["serde"] }
